### PR TITLE
Fix the subfeatures regex.

### LINKED ISSUE #68: Make sure subfeatures are actually subfeatures
Subfeatures were introduced in #66, unfortunately the code was written such that the subfeatures didn't require a dot immediately after the feature name.

This leads to problems like `api.AnimationEffect` being displayed as a subfeature of `api.Animation`, which it is not.

### PR DESCRIPTION
**Pull request by connorshea**
This fixes the regex so that it literally matches a dot after the current feature name.

This way, `api.Animation` will have `api.Animation.cancel` as a subfeature, but not `api.AnimationEffect`.

Fixes #68.

### CODE REVIEW

File: app/controllers/features_controller.rb [hunk 1]
```diff
@@ -91,7 +91,7 @@ def show
     @feature = Feature.friendly.find(params[:slug])
     @browsers = get_browsers
 
-    @subfeatures = Feature.where("name ~* ?", "^#{@feature.name}.*").where.not(slug: params[:slug])
```
Comment (connorshea) [inline app/controllers/features_controller.rb]: Changing `~*` to `~` is unrelated, that just makes it case-insensitive.
